---
title: "Lab 8"
author: "C.Swick"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggpubr)
library(janitor)
library(broom)
library(knitr)
```

```{r}
penguins <- read.csv(here("data", "penguins.csv"))
```

# subset of penguins data for looking at correlations

```{r}
penguins_mod <- penguins %>% 
  select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g) %>% 
  drop_na()

pairs(penguins_mod)

cor(penguins_mod)
  # data correlated with itself should be 1 
  # the higher the numebr the higher the correlation 
  # negative numbers have negative correlation 

```

## Models

### subset data

```{r}
penguins_Adelie_Torgersen <- penguins %>% 
  filter(species == "Adelie") %>% 
  filter(island=="Torgersen") %>% 
  drop_na()
```

## run all the models

```{r}
model_0 <- lm(body_mass_g ~ 1, data = penguins_Adelie_Torgersen) # y = beta naught
model_1 <- lm(body_mass_g ~ flipper_length_mm, data = penguins_Adelie_Torgersen) 
model_2 <- lm(body_mass_g ~ sex, data = penguins_Adelie_Torgersen) # sex will be a dummy variable, all 0 and 1 #t-test
model_3 <- lm(body_mass_g ~ flipper_length_mm + sex, data = penguins_Adelie_Torgersen) # multiple regression 

#model outputs 
model_0_out <- summary(model_0)
model_1_out <- summary(model_1)
model_2_out <- summary(model_2)
model_3_out <- summary(model_3)
```

### Table and data gymnastics

```{r}
out_0_tidy <- tidy(model_0) # coefficient info
out_0_glance <- glance(model_0) #model info 

kable(out_0_tidy, format = "markdown", digits = 3, caption = "Test of linear model 0 coefficient")
kable(out_0_glance, format = "markdown", digits = 3, caption = "Test of linear model 0")
```

```{r}
out_1_tidy <- tidy(model_1) # coefficient info
out_1_glance <- glance(model_1) #model info 

kable(out_1_tidy, format = "markdown", digits = 3, caption = "Test of linear model 1 coefficient")
kable(out_1_glance, format = "markdown", digits = 3, caption = "Test of linear model 1")
```

```{r}
out_2_tidy <- tidy(model_2) # coefficient info
out_2_glance <- glance(model_2) #model info 

kable(out_2_tidy, format = "markdown", digits = 3, caption = "Test of linear model 2 coefficient")
kable(out_2_glance, format = "markdown", digits = 3, caption = "Test of linear model 2")
```

```{r}
out_3_tidy <- tidy(model_3) # coefficient info
out_3_glance <- glance(model_3) #model info 

kable(out_3_tidy, format = "markdown", digits = 3, caption = "Test of linear model 3 coefficient")
kable(out_3_glance, format = "markdown", digits = 3, caption = "Test of linear model 3")
```

## Model Selection

```{r}
BIC_list <- c(BIC(model_0), BIC(model_1), BIC(model_2), BIC(model_3))
BIC_list
```

```{r}
model_output <-
  rbind(data.frame(glance(model_0)), data.frame(glance(model_1)),data.frame(glance(model_2)),data.frame(glance(model_3)))

model_output
        
        
```

## Data Gymnastics to make a pretty table

```{r}
model_output <- model_output %>% 
  select(adj.r.squared, BIC)

model_output <- mutate(model_output, delta.BIC = BIC-min(BIC_list))

model_output$model<- c("Model 0", "Model 1", "Model 2", "Model 3")

model_output <- model_output[, c("model", "adj.r.squared", "BIC", "delta.BIC")]

model_output
```

## Output inro R markdown 
```{r}
kable(model_output, format = "markdown", digits = 3, caption = "R-Squared adjusted, BIC, and Delta BIC for the penguin models. Delta BIC >7 indicated models that should be dismissed from further consideration")
```






